name: product_specs_app
version: 1.0.0+1
publish_to: 'none'
description: اپلیکیشن ثبت مشخصات فنی محصولات ووکامرس با ویس و هوش مصنوعی

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  speech_to_text: ^7.4.0

flutter:
  uses-material-design: true
